export enum PermissionName {
  MANAGE_ROLE = 'manage_role',
  DELETE_ROLE = 'delete_role',
  ASSIGN_ROLE = 'assign_role',
  UPDATE_USER_PASSWORD = 'update_user_password',
  UPDATE_VARIABLE = 'update_variable',
  CREATE_PROJECT = 'create_project',
  DELETE_PROJECT = 'delete_project',
  UPDATE_PROJECT = 'update_project',
  CREATE_EXPERIENCE = 'create_experience',
  UPDATE_EXPERIENCE = 'update_experience',
  DELETE_EXPERIENCE = 'delete_experience',
  CREATE_TOOL = 'create_tool',
  UPDATE_TOOL = 'update_tool',
  DELETE_TOOL = 'delete_tool',
}
