name: portfolio-backend

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-backend
    restart: unless-stopped
    env_file: [.env]
    environment:
      DATABASE_URL: postgresql://postgres:test1234%40@db:5432/portfolio
      SHADOW_DATABASE_URL: postgresql://postgres:test1234%40@shadow-db:5432/shadow_portfolio
    ports:
      - 3101:3101
    volumes:
      - uploads-data:/usr/src/app/uploads
    networks:
      - portfolio-backend-network
      - portfolio-shadow-network
      - traefik_public
    depends_on:
      db:
        condition: service_started
      shadow-db:
        condition: service_started
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.portfolio-backend.rule=Host(`server.alisoliman.net`)'
      - 'traefik.http.routers.portfolio-backend.entrypoints=websecure'
      - 'traefik.http.routers.portfolio-backend.service=portfolio-backend'
      - 'traefik.http.routers.portfolio-backend.tls.certresolver=letsencrypt'
      - 'traefik.http.services.portfolio-backend.loadbalancer.server.port=3101'
      - 'traefik.http.services.portfolio-backend.loadbalancer.server.scheme=http'
      - 'traefik.http.services.portfolio-backend.loadbalancer.passhostheader=true'
  db:
    image: postgres:17-alpine
    container_name: portfolio-db
    ports:
      - 5437:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test1234@
      POSTGRES_DB: portfolio
    networks:
      - portfolio-backend-network
    volumes:
      - portfolio-postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: portfolio-pgadmin
    restart: unless-stopped
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ali@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Test1234@
    depends_on:
      - db

  shadow-db:
    image: postgres:17-alpine
    container_name: shadow_portfolio
    ports:
      - 5438:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test1234@
      POSTGRES_DB: shadow_portfolio
    networks:
      - portfolio-shadow-network
    volumes:
      - shadow-portfolio-postgres-data:/var/lib/postgresql/data

networks:
  portfolio-backend-network:
    driver: bridge
  portfolio-shadow-network:
    driver: bridge
  traefik_public:
    external: true

volumes:
  portfolio-postgres-data:
  shadow-portfolio-postgres-data:
  uploads-data:
