version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5435:5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: restaurant
    networks:
      - freecodecamp
  test-db:
    image: postgres:13
    ports:
      - 5435:5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: restaurant
    networks:
      - freecodecamp
networks:
  freecodecamp:
